### ISSUE TITLE
CSP error on opera

### ISSUE THREAD

**Issue by Gifkun** [KevinParnell/OneeChan#1]
Having a similar error to the CSP error but on opera and the list for the Ublock origin filter doest work.

**Comment by KevinParnell** [comment]
Can you post the error? I don't use Opera so I'm not sure what your error is.

**Comment by Twilicious** [comment]
Pretty sure Opera has a built in adblocker, not sure if that has anything to do with it but just though i'd mention it.

**Comment by KevinParnell** [comment]
I think you're right. I haven't used Opera but I think it does have a built in ad blocker. If that is the case then that is probably the issue. There's probably ways around that though (either edit the filters for it or disable it and use something like uBlock Origin).

**Comment by Gifkun** [comment]
Here is a pic of the message, I have deactivated the opera blocker and have
the same problom still I use uBlock origin and even when I deactivate it it
still gives me the prompt.

**Comment by KevinParnell** [comment]
Can you post the pic please? It would also be great if you can copy and paste it I to text format as well.

**Comment by Gifkun** [comment]
I did, did it not show? Also I figure the problem I was running a script
blocker and had to allow 4channel script to run. It was weird for me since
4chan X works for me even with the script blocker.

Thanks for the help.

**Comment by KevinParnell** [comment]
Didn't show up for me, sorry. And I'm glad you were able to fix it, I'll close the thread now.
<img width="1440" alt="screen shot 2018-11-26 at 11 32 25 am" src="https://user-images.githubusercontent.com/15918185/49027816-0c033200-f16f-11e8-8be6-8b8e545871bb.png">
