### ISSUE TITLE
Themes Aren't Saving Across Boards?

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [KevinParnell/OneeChan#10]
So themes aren't saving across boards, they only save per board. So for example if I go on /r/ then go to /b/ I have to go add the theme again. Not sure why I'm having this issue.

I'm kinda new to 4chan and these extensions, I peeked at the settings and the faq's of the githubs but didn't see anything. I have 4chanX installed and OneeChan through Greasemonkey on Firefox.

**Comment by Z3ROGRAV1TYx** [comment]
Still can't figure this out. Not sure if it's a setting I'm missing or if it's a bug or something?

**Comment by KevinParnell** [comment]
I just tested it and can't reproduce it.

**Comment by Sipeari** [comment]
I'm having the same issue.
Seems that oneechan settings does not transfer between 4chan and 4channel boards.
It happens when i'm using Greasemonkey 4.7 and Firefox 66.0.3 (64-bit).

It works fine for me in chrome, so i'm guessing it's either a setting i have enabled in firefox or firefox itself.

**Comment by Z3ROGRAV1TYx** [comment]
@Sipeari thanks yeah, finally someone with the same issue. I have cookies and cache enabled so not sure the deal.

**Comment by KevinParnell** [comment]
Not too sure what the issue is, I'll check my discord and see if others have the same issue with ff.

**Comment by pizzadude** [comment]
I can't reproduce this issue on Firefox. I use Violentmonkey instead of Greasemonkey though.

**Comment by Sipeari** [comment]
Just a little update.
It seems to be specific to Greasemonkey.
I switched to Violentmonkey and the settings are applying fine to both 4chan and 4channel boards now.

**Comment by KevinParnell** [comment]
I updated the readme to recommend violentmonkey to firefox users
