### ISSUE TITLE
Dear anime weab 

### ISSUE THREAD

**Issue by Spangonagornomb** [KevinParnell/OneeChan#12]
Stop make the world a worst place thats ugly and gay you anime weab 

the plugin is fucking ugly 
please die FUCKING NIGGER

**Comment by KevinParnell** [comment]
Don't make me implement a CoC :wokekevin:
![Woke kevin](https://user-images.githubusercontent.com/15918185/55816432-3f13e580-5ac0-11e9-894c-137dcd1166aa.png)
