### ISSUE TITLE
Can't start a new thread?

### ISSUE THREAD

**Issue by Snow344** [KevinParnell/OneeChan#14]
<img src=https://i.imgur.com/NpGNrf1.png>
In the left: 4chan X + Oneechan

In the right: Only 4chan X
How do I fix this?

**Comment by KevinParnell** [comment]
![Annotation 2019-06-02 020059](https://user-images.githubusercontent.com/15918185/58757419-537dc880-84da-11e9-920a-8186398a60f0.png)
I am unable to reproduce this.

**Comment by Snow344** [comment]
Ah well, this is weird.

**Comment by KevinParnell** [comment]
Try using a different theme or looking through your settings, you may have changed something.

**Comment by Snow344** [comment]
My bad, I had this on.
<img src=https://image.prntscr.com/image/4KHZzV_OQMSywXUrIPzDkg.png>
