### ISSUE TITLE
(You) option shows no checkbox, 4chan X (You) functionality non-functional unless Oneechan also set to track (You)s

### ISSUE THREAD

**Issue by ryanrms** [KevinParnell/OneeChan#16]
Pretty much the title.  With Oneechan disabled, 4chan X shows a check box when clicking on a post's menu which says "You" and is checkable.  Oneechan removes the checkbox, and renders the functionality null (clicking "You" does nothing) unless you have Oneechan track (You)s.  Seems to be a duplication of functionality.

Working all right now that I have (You) tracking enabled in Oneechan, but I thought I'd let you know.

**Comment by KevinParnell** [comment]
You need to enable Show Checkboxes in OneeChan
![image](https://user-images.githubusercontent.com/15918185/72830052-e5933680-3c4d-11ea-9602-88b3832090e8.png)
![image](https://user-images.githubusercontent.com/15918185/72830070-efb53500-3c4d-11ea-9bab-be8b3bc8c708.png)
