### ISSUE TITLE
After Update to 5.8.7. OneeChan no Longer Appears to be Working

### ISSUE THREAD

**Issue by CharAznableLoNZ** [KevinParnell/OneeChan#22]
Before
![image](https://user-images.githubusercontent.com/2172796/61451919-6c69fe00-a90f-11e9-814f-88ac09a632cd.png)

After
![image](https://user-images.githubusercontent.com/2172796/61452259-4002b180-a910-11e9-8492-b2c5d11c999c.png)

No changes were made to the script before or after the update, just the usual auto update.  Console outputs following log file.

`
userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4 ERROR: Execution of script 'OneeChan' failed! Cannot read property 'boards' of undefined
(anonymous) @ userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4
(anonymous) @ userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:5
(anonymous) @ userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4325
(anonymous) @ VM2612:2
E_c @ VM2612:3
ja @ VM2623:65
create @ VM2623:76
c @ VM2623:17
run @ VM2623:17
(anonymous) @ VM2623:78
(anonymous) @ VM2612:2
b @ VM2612:1
(anonymous) @ VM2623:78
(anonymous) @ VM2623:78
TM_back @ VM2623:79
(anonymous) @ VM2623:79
(anonymous) @ VM2612:2
exec_fn @ VM2612:1
(anonymous) @ VM2612:11
V @ VM2612:10
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:28
(anonymous) @ content.js:24
userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4 TypeError: Cannot read property 'boards' of undefined
    at Object.init (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:3355)
    at Object.init (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:991)
    at eval (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4322)
    at Window.tms_390294f6_ca12_4a12_a3de_b07765ee95f1 (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4323)
    at <anonymous>:2:494
    at eval (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4)
    at eval (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:5)
    at Object.eval (userscript.html?id=390294f6-ca12-4a12-a3de-b07765ee95f1:4325)
    at <anonymous>:2:494
    at Object.E_c (<anonymous>:3:306)
`

**Comment by MilkyPL** [comment]
Same problem, happened after updating 4chan-x

**Comment by Nutjob** [comment]
Same here, using OneeChan 5.8.7 with 4chan-X 1.14.9.1

**Comment by Z3ROGRAV1TYx** [comment]
Bumping, same issue here. OneeChan not working.

Firefox: 68.0.1
Violentmonkey: 2.10.5
4chan-X: 1.14.9.1
OneeChan: 5.8.7

**Comment by CharAznableLoNZ** [comment]
@Z3ROGRAV1TYx 
> Also unrelated question to OP, how did you get the /o/Auto banner to the right side of the screen? I assume you set the margins large for the right side of the screen, and small for left.. but where was the option for moving the board banner?

I've had it setup this way for a long time now, it's hard to remember.  So instead of guessing, here is a copy of my 5.7.7 config.
https://mega.nz/#!DYoQAQbB!21QECZvI-oA8e9V5YMupPcq4srwmcE9300nMnkJcJR8

**Comment by nahdoubtit** [comment]
The only updates in the past few days I made and weren't even to the script, really. Most were to the readme, changelog, correcting version numbers throughout files, and removing an extra mascot, no other code has changed so far. Someone in the discord reported the same problem, on chromium edge however, and said a reinstallation fixed the problem. I'm thinking maybe one of the updates within 4chan x has something to do with it. Export the settings for both (bottom left for oneechan, top right for 4chanx), and do a fresh installation of both starting with 4chan x, this should fix your issue. I'm on 4chan x 1.14.9.1 and OneeChan 5.8.7 and it's working. If it keeps happening I'll look into it, I see what might be causing it.

![Screenshot at 2019-07-18 18-18-33](https://user-images.githubusercontent.com/49420169/61496096-20f43600-a989-11e9-8b37-4b303d386094.png)
![Screenshot at 2019-07-18 18-18-40](https://user-images.githubusercontent.com/49420169/61496101-23569000-a989-11e9-9f63-5a79d87a4bcd.png)

**Comment by nahdoubtit** [comment]
Or if one of you who are having issues feel comfortable editing the plugin, open violentmonkey, hit the edit button on the far left on OneeChan (</> button). Jump to line 3349 and you'll see something like: 
`                        if ($SS.conf["Mascots"][j].boards == undefined ||
                            $SS.conf["Mascots"][j].boards.split(",").indexOf($SS.location.board) !== -1)
                            eMascot.push(j);
                    }`

change it to this:
`if ($SS.conf["Mascots"] == undefined || $SS.conf["Mascots"][j].boards == undefined ||
                            $SS.conf["Mascots"][j].boards.split(",").indexOf($SS.location.board) !== -1)
                            eMascot.push(j);
                    }`

(just add **$SS.conf["Mascots"] == undefined ||** to the begging of the if statement there)
since what's happening here is it's not finding the boards property of $SS.conf["Mascots"] since that itself is undefined, and causing the error.

**Comment by Inu90** [comment]
@nahdoubtit Didn't work.
FF 69.0b4
Violentmonkey 2.10.5
4chanX 1.14.9.1

Also, backing up is kind of a tall order since the script doesn't start at all.

**Comment by nahdoubtit** [comment]
> @nahdoubtit Didn't work.
> FF 69.0b4
> Violentmonkey 2.10.5
> 4chanX 1.14.9.1
> 
> Also, backing up is kind of a tall order since the script doesn't start at all.

Reinstalling scripts didn't work? Yeah I just realized saying backing up wouldn't work, sorry. Any chance you can try to edit the script like I mentioned in the post above yours? if you join the discord I can help you in real time. I can't duplicate the issue.

https://discord.gg/BPxUHXj

**Comment by nahdoubtit** [comment]
> @nahdoubtit Didn't work.
> FF 69.0b4
> Violentmonkey 2.10.5
> 4chanX 1.14.9.1
> 
> Also, backing up is kind of a tall order since the script doesn't start at all.

or you can backup data from violentmonkey which will export all userscripts + their data. violentmonkey -> dashboard -> settings -> data export. remove, reinstall, re-add scripts, imported backed up data. the scripts data are saved to a 'violentmonkey' file which is just a text file with json that you can open up with notepad.

**Comment by nahdoubtit** [comment]
@CharAznableLoNZ @Z3ROGRAV1TYx @Nutjob @MilkyPL so far everyone whose had an issue fixed it with reinstalling but thanks to @Inu90 I think we found a fix.

**Comment by nahdoubtit** [comment]
immediate fix is here https://github.com/nahdoubtit/OneeChan/raw/master/builds/OneeChan.user.js until kevin accepts the pull request.

**Comment by nahdoubtit** [comment]
fixed as of 5.8.8 if it doesn't auto update check for updates within violentmonkey / tamper monkey etc.

**Comment by CharAznableLoNZ** [comment]
@nahdoubtit Thank you, 5.8.8 has resolved the issue.
