### ISSUE TITLE
Error evaluating Yotsuba's theme.custom CSS! call to eval() blocked by CSP

### ISSUE THREAD

**Issue by RileyHall** [KevinParnell/OneeChan#24]
Get this popup when browsing any page under 4chan.org, but not 4channel.org. Adding the filters to ublock [per the main page](https://github.com/KevinParnell/OneeChan#adblockpihole-filters-fix) does not fix this. 

I'm on Firefox 68.0.1, 4chan X 1.14.7.4, Violentmonkey 2.10.5, and OneeChan 5.8.8

**Comment by KevinParnell** [comment]
Are you using any other type of blocker or script or plugin?

**Comment by RileyHall** [comment]
Oh dude that was it. Thank you for telling me to check my extensions. The extension Ghostery was causing issues and whitelisting 4chan fixed the error.
