### ISSUE TITLE
QR always forced to sidebar size

### ISSUE THREAD

**Issue by Cruxador** [KevinParnell/OneeChan#25]
The option to "Force QR to Sidebar Size" shows default (checked) behavior whether the box is checked or not; the box can only be distorted vertically within the bounds of the sidebar and cannot be distorted horizontally. 

Chrome Version 76.0.3809.100 (Official Build) (64-bit)
ccd0/4chan X 1.14.12.9
OneeChan 5.8.9

I believe this is an old issue; I haven't known it to work in quite a few years.

**Comment by nahdoubtit** [comment]
Tested on:
Chrome: Version 89.0.4389.82
OneeChan v5.9.3
4chan X version 1.14.20.6 

Firefox 86.0
OneeChan v5.9.3
4chan X version 1.14.20.6 

and no longer seems to be a problem. it should be fixed. if not please re-comment and we can further look into it.
