### ISSUE TITLE
No "start new thread" button

### ISSUE THREAD

**Issue by cocuette** [KevinParnell/OneeChan#26]
The "start new thread" button is not displayed with the etension (version 5.8.9) on, tried turning it off and the button was there

**Comment by KevinParnell** [comment]
I am unable to reproduce this issue 
![image](https://user-images.githubusercontent.com/15918185/72824306-0c983b00-3c43-11ea-8ef0-977a6ea26ded.png)

**Comment by KevinParnell** [comment]
You need to enable this
![image](https://user-images.githubusercontent.com/15918185/72845420-95779c80-3c6c-11ea-97bb-ec04ca026f5d.png)
