### ISSUE TITLE
Helvetica font doesn't work: Uses default Arial

### ISSUE THREAD

**Issue by H4xoltl** [KevinParnell/OneeChan#27]
Tried side by side comparison of Helvetica and Arial, they were identical

**Comment by H4xoltl** [comment]
every other font option works

**Comment by KevinParnell** [comment]
That's because you don't have Helvetica on your computer. I don't have any licenses to the fonts, so it just uses the fonts on your computer. If you are missing the Helvetica font it'll just default if you choose it.

**Comment by KevinParnell** [comment]
`"Font Family": [
                "sans-serif", "Set the default font family.", [{
                    name: "Default",
                    value: "sans-serif"
                }, {
                    name: "Monospace",
                    value: "monospace"
                }, {
                    name: "Ubuntu",
                    value: "Ubuntu"
                }, {
                    name: "Consolas",
                    value: "Consolas"
                }, {
                    name: "Droid Sans",
                    value: "Droid Sans"
                }, {
                    name: "Segoe UI",
                    value: "Segoe UI"
                }, {
                    name: "Calibri",
                    value: "Calibri"
                }, {
                    name: "Arial",
                    value: "Arial"
                }, {
                    name: "Lucida Grande",
                    value: "Lucida Grande"
                }, {
                    name: "Helvetica",
                    value: "Helvetica"
                }]`

directly from the script.
