### ISSUE TITLE
Duplicating theme and non-working custom theme.

### ISSUE THREAD

**Issue by theorist-complex** [KevinParnell/OneeChan#30]
Im not really even sure whats happening here, but its happening in both latest version of Waterfox Classic and an updated version of regular Firefox. 4chan X and Onee are both updated...in fact this problem didnt start until Oneechan updated from v5.8.9 to this latest version 5.9.1

So, once OneeChan updated, my theme was automatically switched to the new Stalenhag theme without asking me or anything. When I tried to switch back to my already installed custom theme it doesn't fully switch. Maybe some colors might change, sometimes nothing.

If I try to edit my custom theme, it fails and pressing the "save" button has no effect at all. I cancel out and then open the theme settings back up and thats when I see that Stalenhag theme has duplicated itself. Here is a picture of what I have right now....it seems to duplicate itself every time you open the theme settings...

![oneechan](https://user-images.githubusercontent.com/7741092/72888762-35204380-3cdc-11ea-8796-302e8e304558.png)

I have reset settings of both  X and Onee in both browsers...restarted...same issues. Tried creating a brand new custom theme from scratch and re-importing previous theme and still getting the same issues in both browsers.

Have no idea whats happening. 

EDIT:

Just checked in latest version of Vivaldi too...same thing.

Everything was fine, then updated X, refreshed, again things are fine, then updated to latest Onee. Refreshed again and my theme was automatically changed from my custom to the Stalenhag. When I went to try and change theme back to my custom, this happened....

![Annotation 2020-01-22 061338](https://user-images.githubusercontent.com/7741092/72889929-cbedff80-3cde-11ea-8c2e-bc3dcdcc14d9.png)

It looks like the Stalenhag theme duplicated itself AND completely duplicated itself OVER my custom theme slot (which would be the 3rd slot instance of Stalenhag in the picture.

**Comment by KevinParnell** [comment]
@theorist-complex @HanGhoul can you update oneechan and see if it still happens? Just updated it and deleted the repeat themes and it seems to work fine again for me.

**Comment by KevinParnell** [comment]
Also so so so sorry that it deleted your custom theme, bad mistake on my part.

**Comment by HanGhoul** [comment]
Works for me again after updating to 5.9.2. Thanks for the fix!

**Comment by KevinParnell** [comment]
Awesome, and it was my pleasure, sorry again it wasn't working properly. I'll wait for theorist to reply before I close the issue.

**Comment by KevinParnell** [comment]
didn't mean to close

**Comment by theorist-complex** [comment]
Sorry, I havent replied yet, been a long day and am just now getting home...

No worries at all about the custom theme, I have backups :D Just wanted to rely all information about what was happening.

Let me give this a go and see if the new update fixes things...and i will edit this post with my findings.

**Comment by KevinParnell** [comment]
I'm so glad it's working. Closing. Thanks again for bringing this to my attention quickly.
