### ISSUE TITLE
Mascot Selection Changes

### ISSUE THREAD

**Issue by QuillOmega0** [KevinParnell/OneeChan#32]
Mascot selection seems to change from update by update, my suspicion is that whatever marks which mascots to use doesn't keep track of the selection of the mascots when ones are removed or added

**Comment by nahdoubtit** [comment]
This is a known issue. The dialog doesn't save it by mascot, rather just position. When a new mascot is added to the top of the selection, or removed, it changes the position of the mascots, and changes what ones you have selected. 
#18
