### ISSUE TITLE
Backlink problems

### ISSUE THREAD

**Issue by marcox199** [KevinParnell/OneeChan#34]
Too many backlinks on number mode will overflow and cover a post. Also I'd prefer if I could set them to the left.

**Comment by KevinParnell** [comment]
Can you post an example please

**Comment by marcox199** [comment]
I'm sorry, do to that issue, I have no longer been using oneechan. However I do remeber that after 2 or 3 rows of backlings, they broke out of the bounding box and stated invading the text.

________________________________
De: Kevin Parnell <notifications@github.com>
Enviado: sábado, 5 de diciembre de 2020 11:27 p. m.
Para: KevinParnell/OneeChan <OneeChan@noreply.github.com>
CC: marcox199 <marcolopgut@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [KevinParnell/OneeChan] Backlink problems (#34)


Can you post an example please
