### ISSUE TITLE
Theme doesn't load on page startup

### ISSUE THREAD

**Issue by The1Penguin** [KevinParnell/OneeChan#35]
The theme that i have chosen doesn't load on page load.
Image of when webiste is first loaded
![image](https://user-images.githubusercontent.com/49118502/103143458-a94a3f00-4716-11eb-9e69-4972aa7eeac9.png)

I am able to import a custom theme and then choose a theme.

**Comment by KevinParnell** [comment]
what theme?

**Comment by The1Penguin** [comment]
It was "Dark Flat" but after resetting the browser, it works
