### ISSUE TITLE
[Question, Solved] Changing color of the transparent image background?

### ISSUE THREAD

**Issue by bellyrose** [KevinParnell/OneeChan#37]
Is there a way to change the color of the background that shows on transparent images? The default is a very weird color, the images below show a transparent image as a thumbnail and opened and you can see that the background on the thumbnail is an eyesore. If this isn't a feature, would it be possible to add in the near future?
![Image1](https://user-images.githubusercontent.com/34819855/104823172-3bc19800-5816-11eb-9e04-df1eb5c84c21.PNG)
Transparent image thumbnail with ugly BG

![Image2](https://user-images.githubusercontent.com/34819855/104823181-4c720e00-5816-11eb-960e-6af8068110bc.PNG)
Transparent image opened up

**Comment by LovingCivilian** [comment]
Enable "Replace PNG" in 4chan X settings, under "Images and Videos" section. that should do the trick.

**Comment by bellyrose** [comment]
Oh cool, thanks!
