### ISSUE TITLE
Bigger font size support

### ISSUE THREAD

**Issue by beriah** [KevinParnell/OneeChan#8]
I was looking to migrate from StyleChan and while copying over my settings I noticed that font sizes are only supported up to 18px. So I looked at SC and saw that despite the hover description also showing that only 10-18px is supported, it actually does display bigger font sizes if you enter them (19px in my case). So yeah is getting bigger font sizes possible?

**Comment by KevinParnell** [comment]
I'll take a look at it.

**Comment by nahdoubtit** [comment]
Not committed yet, but fixed. min size is now 8, max size will be 40.

**Comment by nahdoubtit** [comment]
fixed as of 5.8.8

**Comment by KevinParnell** [comment]
@nahdoubtit added this feature, sorry for the wait.
